# SPDX-FileCopyrightText: 2017-2021 Alliander N.V. <korte.termijn.prognoses@alliander.com> # noqa E501
#
# SPDX-License-Identifier: MPL-2.0
# config of action in ./workflows/...
feature: ['feature*', 'feat*']
fix: ['fix*','bugfix*','hotfix*']
chore: ['chore*', 'doc*']
