# SPDX-FileCopyrightText: 2017-2022 Contributors to the OpenSTEF project <korte.termijn.prognoses@alliander.com> # noqa E501
#
# SPDX-License-Identifier: MPL-2.0
# config of action in ./workflows/...
# PRs in a new draft are categorized based on their labels.
# Their labels can automatically be determined by an action
name: 'v*update yourself based on setup.py* 🌈'
tag: 'v*update yourself based on setup.py*'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
template: |
  Notes to devs (remove when turning draft into actual release):
  - PRs are automatically categorized based on their label.
    Be helpful by adding labels to uncategorized PRs:)
  - Please bump the version number in setup.py yourself
    and use that in the titel of the release
  
  ## Changes

  $CHANGES
  
