# SPDX-FileCopyrightText: 2017-2022 Contributors to the OpenSTEF project <korte.termijn.prognoses@alliander.com> # noqa E501
#
# SPDX-License-Identifier: MPL-2.0
[tool.pylint.format]
max-line-length = 88

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

