# SPDX-FileCopyrightText: 2017-2025 Contributors to the OpenSTEF project <korte.termijn.prognoses@alliander.com>
#
# SPDX-License-Identifier: MPL-2.0

name: Validate citation

on:
  # Run pipeline on push event of main branch, or when CITATIONS path has changed
  push:
    branches:
      - main
    paths:
      - CITATION.cff
      - .github/workflows/citations.yml
  pull_request:
    paths:
      - CITATION.cff
      - .github/workflows/citations.yml
  # Run pipeline from another workflow
  workflow_call:
  # Run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-citations
  cancel-in-progress: true

jobs:
  validate-citations:
    runs-on: ubuntu-24.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Install R
      run: |
        sudo apt-get update && sudo apt-get install -y r-base
    - name: Validate CITATION.cff
      uses: dieghernan/cff-validator@v4