# SPDX-FileCopyrightText: 2017-2022 Contributors to the OpenSTEF project <openstef@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0
# Automatically label PRs, config in ../pr-labeler.yml
name: PR Labeler
on:
  pull_request_target:
    types: [opened]

jobs:
  pr-labeler:
    permissions:
      contents: read # To read config file
      pull-requests: write # To add labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
        with:
          configuration-path: .github/pr-labeler.yml
